### ISSUE TITLE
Wrong count with preview over 100 chars

### ISSUE THREAD

**Issue by adrenalinedj** [schwarzdavid/bootstrap-email#2]
I have a preview tag with over 100 chars (116 exactly) and I'm facing this issue

> node_modules/bootstrap-email/lib/BootstrapEmail.js:513
			preview.html(content + '&nbsp;'.repeat(100 - content.length));

I think a control should be done to avoid negative count on this operation `100 - content.length`

**Comment by schwarzdavid** [comment]
Hey there,
sorry for my late response. The bug will be fixed in the next release
